<a href="https://colab.research.google.com/github/shitakata/log/blob/main/calc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import math
import numpy.linalg as LA

In [ ]:
H = np.array([[0, -math.sqrt(3)],[-math.sqrt(3), 0] ])
H

array([[ 0.        , -1.73205081],
       [-1.73205081,  0.        ]])

In [ ]:
[v,d] = LA.eig(H)
print(v)
print(d)

[ 1.73205081 -1.73205081]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [ ]:
H = np.array([[0, -math.sqrt(3)],[-math.sqrt(3), 2] ])
H

array([[ 0.        , -1.73205081],
       [-1.73205081,  2.        ]])

In [ ]:
[v,d] = LA.eig(H)
print(v)
print(d)

[-1.  3.]
[[-0.8660254  0.5      ]
 [-0.5       -0.8660254]]


In [ ]:
from sympy import *

In [ ]:
T = Symbol('T')
H = Matrix([[0,T], [T,0]])
H

Matrix([
[0, T],
[T, 0]])

In [ ]:
#固有値
H.eigenvals()

{-T: 1, T: 1}

In [ ]:
#固有ベクトル
H.eigenvects()

[(-T, 1, [Matrix([
   [-1],
   [ 1]])]), (T, 1, [Matrix([
   [1],
   [1]])])]

In [ ]:
#対角行列
H.diagonalize()

(Matrix([
 [-1, 1],
 [ 1, 1]]), Matrix([
 [-T, 0],
 [ 0, T]]))

In [ ]:
T = Symbol('T')
Δ = Symbol('Δ')
H = Matrix([[0,T], [T,Δ]])
H

Matrix([
[0, T],
[T, Δ]])

In [ ]:
#固有値
H.eigenvals()

{Δ/2 + sqrt(4*T**2 + Δ**2)/2: 1, Δ/2 - sqrt(4*T**2 + Δ**2)/2: 1}

In [ ]:
#固有ベクトル
H.eigenvects()

[(Δ/2 - sqrt(4*T**2 + Δ**2)/2, 1, [Matrix([
   [-T/(-Δ/2 + sqrt(4*T**2 + Δ**2)/2)],
   [                                1]])]),
 (Δ/2 + sqrt(4*T**2 + Δ**2)/2, 1, [Matrix([
   [-T/(-Δ/2 - sqrt(4*T**2 + Δ**2)/2)],
   [                                1]])])]

In [ ]:
#対角行列
H.diagonalize()

(Matrix([
 [2*T/(Δ - sqrt(4*T**2 + Δ**2)), 2*T/(Δ + sqrt(4*T**2 + Δ**2))],
 [                            1,                             1]]), Matrix([
 [Δ/2 - sqrt(4*T**2 + Δ**2)/2,                           0],
 [                          0, Δ/2 + sqrt(4*T**2 + Δ**2)/2]]))

In [ ]:
cos(math.pi)

-1.00000000000000

In [ ]:
th = Symbol("th")
A =  Matrix([[cos(th),-sin(th)], [sin(th),cos(th)]])
A

Matrix([
[cos(th), -sin(th)],
[sin(th),  cos(th)]])

In [ ]:
A.transpose()

Matrix([
[ cos(th), sin(th)],
[-sin(th), cos(th)]])

In [ ]:
A.transpose()*H*A

Matrix([
[T*sin(th)*cos(th) + (T*cos(th) + Δ*sin(th))*sin(th),       -T*sin(th)**2 + (T*cos(th) + Δ*sin(th))*cos(th)],
[    T*cos(th)**2 + (-T*sin(th) + Δ*cos(th))*sin(th), -T*sin(th)*cos(th) + (-T*sin(th) + Δ*cos(th))*cos(th)]])

In [ ]:
H = Matrix([[0, -math.sqrt(3)],[-math.sqrt(3), 0] ])
H

Matrix([
[                0, -1.73205080756888],
[-1.73205080756888,                 0]])

In [ ]:
#固有値
H.eigenvals()

{-21650635094611/12500000000000: 1, 21650635094611/12500000000000: 1}

In [ ]:
T = Symbol('T')
U = Symbol('U')
Δ = Symbol('Δ')
H = Matrix([[0,math.sqrt(2)*T,0], [math.sqrt(2)*T,Δ,math.sqrt(2)*T],[0,math.sqrt(2)*T,2*Δ+U]])
H

Matrix([
[                0, 1.4142135623731*T,                 0],
[1.4142135623731*T,                 Δ, 1.4142135623731*T],
[                0, 1.4142135623731*T,           U + 2*Δ]])

In [ ]:
#対角行列
H.diagonalize()

(Matrix([
 [                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

In [ ]:
U=5.5
Δ=2.5
T=2.1
H

Matrix([
[                0, 1.4142135623731*T,                 0],
[1.4142135623731*T,                 Δ, 1.4142135623731*T],
[                0, 1.4142135623731*T,           U + 2*Δ]])

In [ ]:
U=5.5
Δ=2.5
T=2.1
H = Matrix([[0,math.sqrt(2)*T,0], [math.sqrt(2)*T,Δ,math.sqrt(2)*T],[0,math.sqrt(2)*T,2*Δ+U]])
H

Matrix([
[              0, 2.9698484809835,               0],
[2.9698484809835,             2.5, 2.9698484809835],
[              0, 2.9698484809835,            10.5]])

In [ ]:
#対角行列
H.diagonalize()

(Matrix([
 [-1.88574355549085 + 1.35525271560688e-20*I, 5.77002898219502 + 5.42101086242752e-20*I,           0.0919050494863072],
 [-2.31036131594098 - 3.04931861011548e-20*I,                         -4.27673147918224, 0.357818770384591 - 0.e-22*I],
 [                                       1.0,                                       1.0,                          1.0]]),
 Matrix([
 [3.63857695532963 - 0.e-22*I,                            0,                           0],
 [                          0, -2.20124448702369 + 0.e-20*I,                           0],
 [                          0,                            0, 11.5626675316941 - 0.e-21*I]]))

In [ ]:
#固有ベクトル
H.eigenvects()

[(3.63857695532963 - 0.e-22*I, 1, [Matrix([
   [-1.88574355549085 + 2.62067928321618e-28*I],
   [              -2.31036131594098 - 0.e-22*I],
   [                                       1.0]])]),
 (-2.20124448702369 + 0.e-20*I, 1, [Matrix([
   [5.77002898219502 + 2.04010792084748e-25*I],
   [             -4.27673147918224 + 0.e-22*I],
   [                                      1.0]])]),
 (11.5626675316941 - 0.e-21*I, 1, [Matrix([
   [0.0919050494863072 - 5.93500627837162e-26*I],
   [               0.357818770384591 + 0.e-22*I],
   [                                        1.0]])])]

終状態

In [ ]:
U=5.5
Δ=2.5
T=2.1
H = Matrix([[0,math.sqrt(2)*T,0], [math.sqrt(2)*T,Δ-U,math.sqrt(2)*T],[0,math.sqrt(2)*T,2*(Δ-U)+U]])
H

Matrix([
[              0, 2.9698484809835,               0],
[2.9698484809835,            -3.0, 2.9698484809835],
[              0, 2.9698484809835,            -0.5]])

In [ ]:
#固有ベクトル
H.eigenvects()

[(-0.259694532142828 + 0.e-22*I, 1, [Matrix([
   [-0.925338958330501 + 2.72983938712005e-28*I],
   [              0.0809150599419104 + 0.e-20*I],
   [                                        1.0]])]),
 (2.80775698666547 - 0.e-22*I, 1, [Matrix([
   [1.17807808951223 - 4.17429339402833e-28*I],
   [              1.11377971228016 + 0.e-20*I],
   [                                      1.0]])]),
 (-6.04806245452264 + 0.e-22*I, 1, [Matrix([
   [0.917328896029156 + 2.51932676723583e-26*I],
   [              -1.86812980192354 + 0.e-21*I],
   [                                       1.0]])])]

In [ ]:
#対角行列
H.diagonalize()

(Matrix([
 [-0.925338958330501 + 1.35525271560688e-20*I, 1.17807808951223 + 1.35525271560688e-20*I, 0.917328896029156 + 2.71050543121376e-20*I],
 [ 0.0809150599419104 + 4.2351647362715e-22*I,                          1.11377971228016,               -1.86812980192354 + 0.e-21*I],
 [                                        1.0,                                       1.0,                                        1.0]]),
 Matrix([
 [-0.259694532142828 + 0.e-22*I,                           0,                            0],
 [                            0, 2.80775698666547 - 0.e-22*I,                            0],
 [                            0,                           0, -6.04806245452264 + 0.e-22*I]]))